runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(migrate|polls|(telegram|poll)/.*)
  script: main.APP
  login: admin

- url: /(.*\.(ico|jpg))$
  static_files: img/\1
  upload: img/.*\.(ico|jpg)$

- url: /.*
  script: main.APP

libraries:
- name: webapp2
  version: "2.5.2"

- name: ssl
  version: "2.7.11"
